# Generated by Django 2.2 on 2020-05-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userextender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('phnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(auto_now=True)),
                ('USER_TYPE', models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_browser', models.TimeField()),
            ],
        ),
    ]
